const  actionTypes = {
    SET_PROFILE: 'SET_PROFILE',

    FETCH_QUESTIONS: 'FETCH_QUESTIONS',
    FETCH_QUESTIONS_REQUEST: 'FETCH_QUESTIONS_REQUEST',
    FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
    FETCH_QUESTIONS_ERROR: 'FETCH_QUESTIONS_ERROR',
};

export default actionTypes;
