const  actionTypes = {
    INIT_APP: 'INIT_APP',

    RESET_APP_FLOW: 'RESET_APP_FLOW',

    START_QUIZ: 'START_QUIZ',

    QUIZ_FINISHED: 'QUIZ_FINISHED',

    SET_PROFILE: 'SET_PROFILE',

    GET_NEXT_QUESTION: 'GET_NEXT_QUESTION',

    FETCH_QUESTIONS: 'FETCH_QUESTIONS',
    FETCH_QUESTIONS_REQUEST: 'FETCH_QUESTIONS_REQUEST',
    FETCH_QUESTIONS_SUCCESS: 'FETCH_QUESTIONS_SUCCESS',
    FETCH_QUESTIONS_ERROR: 'FETCH_QUESTIONS_ERROR',

    SUBMIT_ANSWER: 'SUBMIT_ANSWER',
    SUBMIT_ANSWER_REQUEST: 'SUBMIT_ANSWER_REQUEST',
    SUBMIT_ANSWER_SUCCESS: 'SUBMIT_ANSWER_SUCCESS',
    SUBMIT_ANSWER_ERROR: 'SUBMIT_ANSWER_ERROR',
};

export default actionTypes;
